function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy as a
%       percentage. In the app, the Models pane displays this overall
%       accuracy score for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 13-Jun-2022 14:57:35


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Mitjana subimatge 1', 'Variancia subimatge 1', 'Skew subimatge 1', 'Kurtosis subimatge 1', 'Mitjana subimatge 2', 'Variancia subimatge 2', 'Skew subimatge 2', 'Kurtosis subimatge 2', 'Mitjana subimatge 3', 'Variancia subimatge 3', 'Skew subimatge 3', 'Kurtosis subimatge 3', 'Mitjana subimatge 4', 'Variancia subimatge 4', 'Skew subimatge 4', 'Kurtosis subimatge 4', 'Mitjana subimatge 5', 'Variancia subimatge 5', 'Skew subimatge 5', 'Kurtosis subimatge 5', 'Mitjana subimatge 6', 'Variancia subimatge 6', 'Skew subimatge 6', 'Kurtosis subimatge 6', 'Mitjana subimatge 7', 'Variancia subimatge 7', 'Skew subimatge 7', 'Kurtosis subimatge 7', 'Mitjana subimatge 8', 'Variancia subimatge 8', 'Skew subimatge 8', 'Kurtosis subimatge 8', 'Mitjana subimatge 9', 'Variancia subimatge 9', 'Skew subimatge 9', 'Kurtosis subimatge 9'};
predictors = inputTable(:, predictorNames);
response = inputTable.Etiqueta;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationSVM = fitcsvm(...
    predictors, ...
    response, ...
    'KernelFunction', 'linear', ...
    'PolynomialOrder', [], ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true, ...
    'ClassNames', categorical({'No-Ulls'; 'Ulls'}));

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
svmPredictFcn = @(x) predict(classificationSVM, x);
trainedClassifier.predictFcn = @(x) svmPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'Kurtosis subimatge 1', 'Kurtosis subimatge 2', 'Kurtosis subimatge 3', 'Kurtosis subimatge 4', 'Kurtosis subimatge 5', 'Kurtosis subimatge 6', 'Kurtosis subimatge 7', 'Kurtosis subimatge 8', 'Kurtosis subimatge 9', 'Mitjana subimatge 1', 'Mitjana subimatge 2', 'Mitjana subimatge 3', 'Mitjana subimatge 4', 'Mitjana subimatge 5', 'Mitjana subimatge 6', 'Mitjana subimatge 7', 'Mitjana subimatge 8', 'Mitjana subimatge 9', 'Skew subimatge 1', 'Skew subimatge 2', 'Skew subimatge 3', 'Skew subimatge 4', 'Skew subimatge 5', 'Skew subimatge 6', 'Skew subimatge 7', 'Skew subimatge 8', 'Skew subimatge 9', 'Variancia subimatge 1', 'Variancia subimatge 2', 'Variancia subimatge 3', 'Variancia subimatge 4', 'Variancia subimatge 5', 'Variancia subimatge 6', 'Variancia subimatge 7', 'Variancia subimatge 8', 'Variancia subimatge 9'};
trainedClassifier.ClassificationSVM = classificationSVM;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2021b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Mitjana subimatge 1', 'Variancia subimatge 1', 'Skew subimatge 1', 'Kurtosis subimatge 1', 'Mitjana subimatge 2', 'Variancia subimatge 2', 'Skew subimatge 2', 'Kurtosis subimatge 2', 'Mitjana subimatge 3', 'Variancia subimatge 3', 'Skew subimatge 3', 'Kurtosis subimatge 3', 'Mitjana subimatge 4', 'Variancia subimatge 4', 'Skew subimatge 4', 'Kurtosis subimatge 4', 'Mitjana subimatge 5', 'Variancia subimatge 5', 'Skew subimatge 5', 'Kurtosis subimatge 5', 'Mitjana subimatge 6', 'Variancia subimatge 6', 'Skew subimatge 6', 'Kurtosis subimatge 6', 'Mitjana subimatge 7', 'Variancia subimatge 7', 'Skew subimatge 7', 'Kurtosis subimatge 7', 'Mitjana subimatge 8', 'Variancia subimatge 8', 'Skew subimatge 8', 'Kurtosis subimatge 8', 'Mitjana subimatge 9', 'Variancia subimatge 9', 'Skew subimatge 9', 'Kurtosis subimatge 9'};
predictors = inputTable(:, predictorNames);
response = inputTable.Etiqueta;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationSVM, 'KFold', 5);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
